### PR TITLE
Initial conversion to translation API

### LINKED ISSUE #28: Any chance on language support ?
Hi, 

great module, works like a charm. 

However I need to manually go through your source code to do a localization (e.g. for German). This is a little tedious. Any chance you'd consider supporting the language translation .json files ?

Thank you very much,
Lars

### PR DESCRIPTION
**Pull request by MikeBishop**
Fixes #28; implements the language API.  Documentation for this is not as rich as I would hope; I had to reverse-engineer the MM2 code a bit and discovered https://github.com/MichMich/MagicMirror/issues/2389 in the process, but I worked around that by using `" "` instead of `""` where it broke things.

@McMornan, I'd like to specifically ask you for three things, if you're willing:

- Provide feedback on whether this conversion enables you to do your German translation properly
- Give me a PR adding the German translation to the repo
- Run it for a few days and see if you notice any text glitches

### CODE REVIEW

**Comment by McMornan** [comment]
Hi, thanks for your efforts! I'll do my best to help !

**Comment by McMornan** [comment]
Hi, I added a language file for Germany (de.json) und made a pull request in a fork. However the size of the graphs for my Tesla powerwall is now screen filling. Also my global language setting from magicmirror does not seem to be used. (language is set to "de" in global config setting in config.js.

**Comment by MikeBishop** [comment]
Hm, I'm not sure what's going on with the graph size, and I don't see that on my machine after switching to German.  I did find the issue with the translations not being used -- two issues, actually.  :-)  Give the merged branch a test?

**Comment by McMornan** [comment]
Yea, did that. Works ! Thanks for your fast reply and support!

 

Von: Mike Bishop <notifications@github.com> 
Gesendet: Donnerstag, 31. Dezember 2020 17:36
An: MikeBishop/MMM-Powerwall <MMM-Powerwall@noreply.github.com>
Cc: McMornan <deutsch.lars@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MikeBishop/MMM-Powerwall] Initial conversion to translation API (#29)

 

Hm, I'm not sure what's going on with the graph size, and I don't see that on my machine after switching to German. I did find the issue with the translations not being used -- two issues, actually. :-) Give the merged branch a test?

**Comment by MikeBishop** [comment]
I'll go ahead and merge this; if there are further "rough" places you'd like to improve in the translation, feel free to send a PR and/or let me know what needs to be rearranged.

**Pull request merged**
